export enum EPayrollPeriodStatus {
  Open = 'open',
  Paid = 'paid',
  Reversed = 'reversed',
}

export enum EPayrollLineItemStatus {
  Pending = 'pending',
  Paid = 'paid',
  Reversed = 'reversed',
}

export enum EPaymentMethod {
  Cash = 'cash',
  BankTransfer = 'bank_transfer',
  Card = 'card',
}

export enum EExpenseSource {
  Manual = 'manual',
  AutoGenerated = 'auto_generated',
}

