default_platform(:ios)

platform :ios do
  desc "Build the app and upload it to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_PATH"],
      in_house: false,
    )

    latest_build = latest_testflight_build_number(api_key: api_key)
    increment_build_number(
      xcodeproj: "App.xcodeproj",
      build_number: (latest_build + 1).to_s,
    )

    build_app(
      workspace: "App.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      output_directory: "output",
      export_options: {
        provisioningProfiles: {
          "app.scheday" => "scheday appstore",
        },
      },
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
    )
  end
end
